# Hacktiv8 Phase 0: Non Graded Challenge 4

---

by [Rifky Aliffa](https://github.com/Penzragon)

Instruction:

Apakah ![Vector](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Cbegin%7Bbmatrix%7D1%20%5C%5C%203%20%5Cend%7Bbmatrix%7D) adalah eigenvector dari ![Matrix](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Cbegin%7Bbmatrix%7D1%20%26%20-1%20%5C%5C%206%26%204%20%5Cend%7Bbmatrix%7D)?

Jika iya, berapakah eigenvalue-nya?


## Import Library

In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True)

## Answer

Membuat vector V

In [3]:
V = [1, 3]
V = np.array(V)
V

array([1, 3])

Membuat Matrix M

In [4]:
M = [[1, -1], [6, 4]]
M = np.array(M)
M

array([[ 1, -1],
       [ 6,  4]])

In [5]:
eigval, eigvec = np.linalg.eig(M)

Melakukan rekonstruksi matrix M dengan menggunakan eigenvalue dan eigenvector.

In [6]:
eigval

array([2.5+1.93649167j, 2.5-1.93649167j])

# NOT DONE YET!!!