# Hacktiv8 Phase 0: Non Graded Challenge 4

---

by [Rifky Aliffa](https://github.com/Penzragon)

Instruction:

Apakah ![Vector](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Cbegin%7Bbmatrix%7D1%20%5C%5C%203%20%5Cend%7Bbmatrix%7D) adalah eigenvector dari ![Matrix](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Cbegin%7Bbmatrix%7D1%20%26%20-1%20%5C%5C%206%26%204%20%5Cend%7Bbmatrix%7D)?

Jika iya, berapakah eigenvalue-nya?


## Import Library

In [1]:
import numpy as np

## Answer

Membuat vector V

In [2]:
V = [1, 3]
V = np.array(V)
V

array([1, 3])

Membuat Matrix M

In [3]:
M = [[1, -1], [6, 4]]
M = np.array(M)
M

array([[ 1, -1],
       [ 6,  4]])

Mencari eigenvalue dan eigenvector dari matrix M

In [4]:
eigval, eigvec = np.linalg.eig(M)

In [5]:
eigval

array([2.5+1.93649167j, 2.5-1.93649167j])

In [6]:
eigvec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

Formula to find Eigenvalue and Eigenvector:

$A$ $x$ = $λ$ $x$

Membuat kondisi dimana jika hasil matrix (M) dikalikan dengan vector (V) sama dengan eigenvalue dari matrix (M) dikalikan dengan vector (V).

In [7]:
if (M @ V == eigval * V).any():
    print(f'Vector V adalah eigenvector dari matrix M dengan eigenvalue = {eigval}.')
else:
    print('Vector V bukan merupakan eigenvector dari matrix M.')
    print(f'Eigenvector dari matrix M adalah: \n{eigvec}')

Vector V bukan merupakan eigenvector dari matrix M.
Eigenvector dari matrix M adalah: 
[[-0.23145502+0.29880715j -0.23145502-0.29880715j]
 [ 0.9258201 +0.j          0.9258201 -0.j        ]]


Vector ![Vector](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Cbegin%7Bbmatrix%7D1%20%5C%5C%203%20%5Cend%7Bbmatrix%7D) ***BUKAN*** merupakan eigenvector dari matrix ![Matrix](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Cbegin%7Bbmatrix%7D1%20%26%20-1%20%5C%5C%206%26%204%20%5Cend%7Bbmatrix%7D).